language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# Install dependencies
install:
  - python setup.py install

# Script to run
script:
  - echo "OKAY"

# Github Branch
branches:
  only:
    - master
